### ISSUE TITLE
npm install agile-sdk --save doesn't install dependency "lodash"

### ISSUE THREAD

**Issue by dpap** [Agile-IoT/agile-sdk#35]

**Comment by craigmulligan** [comment]
Hey @dpap, lodash is a dev dependency so it won't be included when you install it as a dependency? How are you trying to use the sdk?

**Comment by dpap** [comment]
Well even if I run export NODE_ENV=production; npm start 
I still get the error. 

module.js:472
    throw err;
    ^

Error: Cannot find module 'lodash/clone'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/agileIot/quantified-self/node_modules/agile-sdk/dist/index.js:39:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/agileIot/quantified-self/agileSync.js:20:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by craigmulligan** [comment]
You are right 👍 , we obv didn't pick it up because the other modules installed lodash themselves. :) Will push a fix soon.

**Comment by craigmulligan** [comment]
Fixed with `v1.22`.
